### PR TITLE
fix(types): add watchQuery function type

### LINKED ISSUE #263: Impossible to use watchQuery with vue-property-decorator
I've tried to use `watchQuery()` inside a component decorator, but it didn't work. Is it possible to use `watchQuery()` at all? Or should i switch to a nuxt-property-decorator?

### PR DESCRIPTION
**Pull request by danielroe**
closes #263

### CODE REVIEW

File: packages/types/app/vue.d.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ declare module 'vue/types/options' {
     scrollToTop?: boolean
     transition?: string | Transition | ((to: Route, from: Route) => string)
     validate?(ctx: Context): Promise<boolean> | boolean
-    watchQuery?: boolean | string[]
+    watchQuery?: boolean | string[] | ((to: Route['query'], from: Route['query']) => boolean)
```
Comment (kevinmarrec) [inline packages/types/app/vue.d.ts]:
```suggestion
    watchQuery?: boolean | string[] | ((newQuery: Route['query'], oldQuery: Route['query']) => boolean)
```
Maybe these function param names are more relevant ? dunno
